### ISSUE TITLE
Allow scrubbing non-string parameters

### ISSUE THREAD

**Issue by danspark** [VerifyTests/Verify.EntityFramework#497]
#### Is the feature request related to a problem

Yes. I would like to do something similar to what is done to `Guid`, `DateOnly` and others. But it doesn't seem to be possible if they're not strings.

I have the following test (reduced for clarity)

```csharp
public async Task Query_ShouldSendExpectedParameters()
{
  long processId = GetProcessId();

  EfRecording.StartRecording();
  
  await Repository.GetCountAsync(processId);

  var recording = EfRecording.FinishRecording().Single();

  await Verify(recording);
}
```

My verified file looks something like this:

```
{
  Type: ReaderExecutedAsync,
  HasTransaction: false,
  Parameters: {
    @__processId_0 (Int64): ProcessId
  },
  Text:
SELECT COUNT(*)
FROM (
    SELECT DISTINCT [d].[Item]
    FROM [dbo].[Items] AS [d]
    WHERE [d].[ProcessId] = @__processId_0
) AS [t]
}
```

However, I cannot change the `@__processId_0` parameter in the verification unless I explicitly change the `LogEntry.Parameters` to be a string:

```csharp
foreach (var key in recording.Parameters.Keys)
{
  recording.Parameters[key] = recording.Parameters[key].ToString() ?? string.Empty;
}

// verification
await Verify(recording).ScrubLinesWithReplace(_ => _.Replace(processId.ToString(), "ProcessId"));
```

If I don't do this, my verification fails with the following received file:

```
{
  Type: ReaderExecutedAsync,
  HasTransaction: false,
  Parameters: {
    @__processId_0 (Int64): 1
  },
  Text:
SELECT COUNT(*)
FROM (
    SELECT DISTINCT [d].[Item]
    FROM [dbo].[Items] AS [d]
    WHERE [d].[ProcessId] = @__processId_0
) AS [t]
}
```

Where 1 is the current ID of the test. It will subsequently fail with 2, 3, 4 and such.

#### Describe the solution

It would be nice to have something like `Date` and `Guid`'s scrubbing, but `int` and `long` (or maybe for every type)

#### Describe alternatives considered

Forcing the parameters to be string works, but it's not ideal.

**Comment by SimonCropp** [comment]
can u share a failing unit test in a pull request
